### ISSUE TITLE
When time slots are loading, please add a spinner instead of hiding full calendar

### ISSUE THREAD

**Issue by kieranklaassen** [GetOccasion/modern-checkout#21]
1. Go to https://occasion-staging-pr-6836.herokuapp.com/xp/mde-brgfjcvyfthd6_qchq

Expect the calendar to load as fast as normal

Actually, it is loading very slowly because the first time slot is far in the future. It should use the `product.first_time_slot_starts_at` to start on March 2019 and load quickly

**Comment by nicklandgrebe** [comment]
Can't replicate - the first request is for March 2019

**Comment by kieranklaassen** [comment]
ok then we need a spinner for the time slots to load since they are pretty slow sometimes
