### ISSUE TITLE
Skipping attendee information

### ISSUE THREAD

**Issue by kieranklaassen** [GetOccasion/modern-checkout#23]
Place on a per attendee basis

![classes](https://user-images.githubusercontent.com/209089/42656883-483d4b1a-85e6-11e8-9814-a26069986f1d.png)
 instead of all attendees:

**Comment by nicklandgrebe** [comment]
To fix:

in `occsn-checkout`:

`reducers/appReducer.js`

- Change `skipAttendees` from bool to object
- Change reducer logic for `SET_SKIP_ATTENDEES` to use `action.attendee` and `action.skip` to set `skipAttendees[action.attendee] = action.skip`

`actions/appActions.js`

- Change setSkipAttendees to accept two args: `attendee`, and `skip`
- Change return object to:
```
{
  type: actions.SET_SKIP_ATTENDEES,
  attendee,
  skip
}
```

`components/Order/Attendees.jsx`

- Use `skipAttendees` variable already passed down to component
- Remove `!skipAttendees` logic wrapping `Collection`

Change Collection definition to:

```
<Collection component={Attendee} componentProps={{ questions, skipAttendees }}
                      reflection='attendees' subject={subject.attendees()}>
          </Collection>
```

`components/Order/Attendees/Attendee.jsx`

- Add `skipAttendees: PropTypes.object` to `propTypes`
- import `Input` from `reactstrap`
- Add `Input type=checkbox` to `CardBody` (see `components/Order/Answers/Checkbox.jsx` for example)
  - Add `onChange={(e) => setSkipAttendees(indexOf, e.target.checked}` prop to checkbox `Input`
