### ISSUE TITLE
Sections are bleeding into each other

### ISSUE THREAD

**Issue by aksh0925** [GetOccasion/modern-checkout#34]
To replicate:
1. Go here - https://occasion-staging-pr-6836.herokuapp.com/xp/udvoencdgm7ol8digv_huq
2. Scroll down to the Pricing, Policy and Attendee sections.

Expected:
1. Perhaps something that separates the sections like a horizontal line

Actual:
Sections are bleeding into each other - https://occasion-staging-pr-6836.herokuapp.com/xp/udvoencdgm7ol8digv_huq

**Comment by kieranklaassen** [comment]
duplicate
