### ISSUE TITLE
Adding spin button should be set to 0 unless otherwise specified

### ISSUE THREAD

**Issue by kieranklaassen** [GetOccasion/modern-checkout#49]
![modern_checkout](https://user-images.githubusercontent.com/209089/42713859-8fa008be-86b6-11e8-8bae-8cc563027efe.png)

![noisacco_-_listing](https://user-images.githubusercontent.com/209089/42713870-9be6babe-86b6-11e8-9293-fd9fe5f8daeb.png)

**Comment by nicklandgrebe** [comment]
The problem with this is that if it is zero yet impacts attendance, then the quantity is zero, which is invalid on the server

Can one of you fix this issue on the server if thats the right move?

**Comment by kieranklaassen** [comment]
That's a perfectly fine use case to have impacts attendance and 0

**Comment by pelletencate** [comment]
@nicklandgrebe Example:

Q1: How many meat dishes?
Q2: How many veggie dishes?

If both are 0, it's invalid. If **any** one is positive, **everything** is valid.

**Comment by nicklandgrebe** [comment]
ah, then this is an issue with displaying errors, we currently don't output any errors from the `answers` relationship, so you'll have to detect this one when quantity is zero and then display it probably near the missing answers

**Comment by pelletencate** [comment]
Problem is, answers aren't really "missing", they're really all individually correct, but combined they render an order with qty 0.

I'll see what I can do about this.

**Comment by pelletencate** [comment]
Fixed thru https://github.com/GetOccasion/occasion/issues/6876
