### ISSUE TITLE
Security badge

### ISSUE THREAD

**Issue by kieranklaassen** [GetOccasion/modern-checkout#78]
https://help.shopify.com/en/themes/customization/store/add-security-badge

**Comment by nicklandgrebe** [comment]
Where should the badge be placed?

**Comment by pelletencate** [comment]
It now shows a Shopify badge. Doesn't Spreedly have one? Or should it be an operator-infused one?

**Comment by pelletencate** [comment]
Issue moved to [GetOccasion/occsn-checkout #59](https://github.com/GetOccasion/occsn-checkout/issues/59) via [**ZenHub**](https://www.zenhub.com/)
